<BackgroundColor>:
    background_color: 0, 0.8, 0.1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<layoutColor>:
    background_color: 0.33, 0.84, 0.75, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos